### PR TITLE
fix: translate glyphs before the negative y scaling to bottom align o…

### PR DESCRIPTION
**Pull request by eburghar**
See #170

### CODE REVIEW

**Comment by eburghar** [comment]
I changed the svg template because a negative ascent and a descent of the size of the glyps was quiet weird. Normally the ascent should be the full height and the descent a fraction of that height where the baseline should be positioned.

**Review by mondeja — COMMENTED** [review]
Great, thank you!

I've only a question. Why should not be de `descent` 0 as we are dealing with icons? I've done a comparison adding `border: 1px solid black` to `i.si` elements and, at least in the test page, inside their same DOM elements, icons look centered when setting `descent="0"`:

#### `descent="240"`

image

#### `descent="0"`

image

**Comment by eburghar** [comment]
Yes, you are right. It is better. I think I saw that setting in awesome font but my guess is that each icon define its own baseline and descent in thta case is set to the max value. As none of the icons of simple icons set a baseline a descent of 0 is definitively better.

**Comment by ineshbose** [comment]
Sorry for the bump and ping @mondeja but it's been a week and hoping to have this merged soon please so the LaTeX wrapper can also implement the fix as well! 😄

**Review by mondeja — APPROVED** [review]
Looks great, thanks! 👍🏼

**Pull request merged**
