### PR TITLE
Add composer.json to publish to Packagist

### PR DESCRIPTION
**Pull request by ericcornelissen**
This Pull Request is based on https://github.com/simple-icons/simple-icons/pull/1611.

This adds a `composer.json` file which, combined with [our GitHub releases](https://github.com/simple-icons/simple-icons-font/releases), will allow us to publish the font to [Packagist](https://packagist.org/) in addition to NPM similar to [the simple-icons package on Packagist](https://packagist.org/packages/simple-icons/simple-icons). The documentation in the README has also been updated to include a section on PHP usage.

### CODE REVIEW

**Comment by mondeja** [comment]
> This adds a composer.json file which, combined with our GitHub releases, will allow us to publish the font to Packagist in addition to NPM similar to the simple-icons package on Packagist.

I don't know how Packagist works, but this suggest that when you do a Github release, the code of the repository is released a Packagist package, could you confirm it @ericcornelissen?

**Comment by ericcornelissen** [comment]
I also only have a basic understanding of how Packagist works; but to the best of my knowledge, on the publishing side, Packagist looks at two things: git branches and git tags (which are behind GitHub releases). This allows Packagist users to specify dependencies in terms of one of these two. For example, if you look at [the Packagist page for simple-icons](https://packagist.org/packages/simple-icons/simple-icons) you see that the sidebar has a list of numbers (corresponding to git tags or versions) and some `dev-xxx` entries (corresponding to git branches, prefixed with "dev-").

**Review by mondeja — APPROVED** [review]
OK, so I guess that the badge won't be broken after merge, right?

**Comment by ericcornelissen** [comment]
> OK, so I guess that the badge won't be broken after merge, right?

More or less, I will have to tell Packagist to start reading the repository and then it might take a while before it works. I'm pretty sure the URLs for the badge are correct as I just took the ones from [the simple-icons README](https://github.com/simple-icons/simple-icons/blob/ce27500858d38947e09ebf165d2a999320291347/README.md) and added "-font". If it turns out something is wrong anyway we can patch it in a separate commit :slightly_smiling_face:

**Comment by mondeja** [comment]
In that case, lets go ahead

**Comment by ericcornelissen** [comment]
I added this project on Packagist, see: https://packagist.org/packages/simple-icons/simple-icons-font

It still doesn't quite work, though the message on the badge has changed. I believe, based on the logs you get when clicking ` View Log` this is because existing release don't have a `composer.json` file. @mondeja, do you think we should release a patch (v4.10.1) to verify this?

**Comment by mondeja** [comment]
Maybe better, could you add a commit removing the badge and we will add it next week? Just to keep the repository looking right.

**Comment by mondeja** [comment]
Retored Packagist badge in https://github.com/simple-icons/simple-icons-font/commit/cc893b90ce2a6ad3fa9804138e6e5473588bc3fe

**Comment by ericcornelissen** [comment]
Thanks @mondeja :tada:

**Pull request merged**
