### PR TITLE
Generate minified CSS at build process

### LINKED ISSUE #42: Minimize package CSS
As per [a discussion](https://github.com/simple-icons/simple-icons-font/pull/6#discussion_r304974659) in #6, we should consider minimizing the CSS of the package, especially if #39 gets merged.

### PR DESCRIPTION
**Pull request by mondeja**
Closes #42

### CODE REVIEW

**Comment by ericcornelissen** [comment]
Why not, rather then running the build CSS function twice, outputting it the first time and minifying it then? Also, why not just use an actual CSS minifier? I don't think we will get much out of it now, other then maybe optimized colors (e.g. `#000` instead of `#000000`), but it should be more robust for the future.

**Comment by mondeja** [comment]
> why not just use an actual CSS minifier?

I'm not against it. I suppose that is the eternal conflict between delegate in third party libraries vs cook it yourself and not been abandoned.

> I don't think we will get much out of it now, other then maybe optimized colors (e.g. #000 instead of #000000).

Is not better to manage this in `simple-icons` directly?

**Comment by ericcornelissen** [comment]
> I'm not against it. I suppose that is the eternal conflict between delegate in third party libraries vs cook it yourself and not been abandoned. ~Do you recommend a library?~ I've used [jakubpawlowicz/clean-css](https://github.com/jakubpawlowicz/clean-css).

I suppose, though it should be easy enough to change minifiers at a later point (or decide to use a custom one).

If you want to do the proper _Software Engineering_  thing to guard against this we could create a new JS module `scripts/css-minifier.js` and export a function there that is used in `scripts/build.js`. That way we have an unchanging internal "API" for minifying CSS and can more easily switch from package to package (to custom implementation). I would be fine with that change if you like it :slightly_smiling_face: But it might be a bit overkill for this project :upside_down_face: 


> What about handle this in `simple-icons`?

I'd be against that as one could use `simple-icons` in a place where `#000` is not recognized, whereas the CSS file here should be parsed by a CSS compliant rendering engine which should recognize that `#000` means `#000000`. To be completely honest, I never remember what e.g. `#123` is when you write it in full, `#112233` or `#123123`? If only for that reason I would keep the 6-character variant in `simple-icons`, since we display it on the website (though, arguably, we can add a conversion for this when the website is generated...)

**Review by ericcornelissen — APPROVED** [review]

**Comment by mondeja** [comment]
> I would be fine with that change if you like it :slightly_smiling_face: But it might be a bit overkill for this project :upside_down_face:

Yes, I think also that is too much for this project, so let's keep the build process simple, at least for now.

> I'd be against that as one could use simple-icons in a place where #000 is not recognized

You're totally right about it.

**Pull request merged**
