### PR TITLE
Disable Renovate dependency dashboard

### PR DESCRIPTION
**Pull request by mondeja**
Issue: #132 (it will be automatically closed by @renovate-bot spammer 😆 ).

### CODE REVIEW

**Comment by ericcornelissen** [comment]
I agree, we can always opt in later (a bit annoying that the default is opt in 😑). Let's see if the behavior is expected here before we merge the related Pull Requests in the other projects.

**Comment by mondeja** [comment]
> Let's see if the behavior is expected here before we merge the related Pull Requests in the other projects.

Could you explain this? The expected behaviour is 1) @renovate-bot don't open more issues or 2) the issue is closed?

**Comment by ericcornelissen** [comment]
I was primarily talking about if the issue would be closed (which it did), but now I'm also wondering when we're getting the Pull Request that updates the dependencies mentioned in #132 🤔

**Comment by mondeja** [comment]
Sounds crazy, but after this movement I'm now worrying about the same 🤣
I've [questioned about it](https://github.com/renovatebot/renovate/discussions/11415#discussioncomment-1254714) in the Renovate's discussion of the topic.

**Comment by mondeja** [comment]
[Quoting Renovate developer](https://github.com/renovatebot/renovate/discussions/11415#discussioncomment-1254837):

> Whatever happens with the dashboard will not affect any updates from Renovate PRs.

**Comment by ericcornelissen** [comment]
Thanks for asking about this @mondeja, I think we can go ahead and apply this changes in all projects.

**Pull request merged**
